-- PostgreSQL / Supabase Schema DDL for Secure College Admin Panel

-- 1. Admins Table
CREATE TABLE IF NOT EXISTS admins (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    email TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    full_name TEXT NOT NULL,
    role TEXT NOT NULL CHECK(role IN ('super_admin', 'faculty_admin', 'staff_admin')),
    two_factor_secret TEXT DEFAULT NULL,
    two_factor_enabled INTEGER DEFAULT 0,
    status TEXT DEFAULT 'active' CHECK(status IN ('active', 'disabled')),
    failed_login_attempts INTEGER DEFAULT 0,
    lock_until TIMESTAMPTZ DEFAULT NULL,
    last_login TIMESTAMPTZ DEFAULT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Password Resets Table
CREATE TABLE IF NOT EXISTS password_resets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id BIGINT NOT NULL REFERENCES admins(id) ON DELETE CASCADE,
    token_hash TEXT UNIQUE NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    used INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Departments Table
CREATE TABLE IF NOT EXISTS departments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Faculty Table
CREATE TABLE IF NOT EXISTS faculty (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    faculty_id_num TEXT UNIQUE NOT NULL,
    full_name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    phone TEXT,
    department_id BIGINT REFERENCES departments(id) ON DELETE SET NULL,
    designation TEXT NOT NULL,
    qualification TEXT,
    photo_path TEXT,
    status TEXT DEFAULT 'active' CHECK(status IN ('active', 'on_leave', 'inactive')),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Courses Table
CREATE TABLE IF NOT EXISTS courses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_code TEXT UNIQUE NOT NULL,
    title TEXT NOT NULL,
    department_id BIGINT REFERENCES departments(id) ON DELETE CASCADE,
    credits INTEGER NOT NULL,
    semester INTEGER NOT NULL,
    faculty_id BIGINT REFERENCES faculty(id) ON DELETE SET NULL,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Students Table
CREATE TABLE IF NOT EXISTS students (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    roll_number TEXT UNIQUE NOT NULL,
    full_name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    phone TEXT,
    department_id BIGINT REFERENCES departments(id) ON DELETE SET NULL,
    semester INTEGER NOT NULL DEFAULT 1,
    enrollment_year INTEGER NOT NULL,
    status TEXT DEFAULT 'active' CHECK(status IN ('active', 'graduated', 'suspended')),
    document_path TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. Notices Table
CREATE TABLE IF NOT EXISTS notices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    category TEXT NOT NULL CHECK(category IN ('academic', 'examination', 'event', 'admission', 'general')),
    content TEXT NOT NULL,
    target_audience TEXT DEFAULT 'all' CHECK(target_audience IN ('all', 'students', 'faculty', 'staff')),
    priority TEXT DEFAULT 'normal' CHECK(priority IN ('low', 'normal', 'high', 'urgent')),
    attachment_path TEXT,
    publish_date TIMESTAMPTZ DEFAULT NOW(),
    expiry_date TIMESTAMPTZ,
    is_published INTEGER DEFAULT 1,
    created_by BIGINT REFERENCES admins(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. Admissions Applications Table
CREATE TABLE IF NOT EXISTS applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_no TEXT UNIQUE NOT NULL,
    applicant_name TEXT NOT NULL,
    email TEXT NOT NULL,
    phone TEXT NOT NULL,
    applied_department_id BIGINT REFERENCES departments(id) ON DELETE SET NULL,
    previous_marks_percentage REAL,
    document_path TEXT,
    status TEXT DEFAULT 'pending' CHECK(status IN ('pending', 'approved', 'rejected', 'under_review')),
    reviewer_notes TEXT,
    reviewed_by BIGINT REFERENCES admins(id) ON DELETE SET NULL,
    reviewed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 9. Audit Activity Logs Table
CREATE TABLE IF NOT EXISTS audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id BIGINT REFERENCES admins(id) ON DELETE SET NULL,
    admin_username TEXT NOT NULL,
    action TEXT NOT NULL,
    entity_type TEXT NOT NULL,
    entity_id BIGINT,
    details TEXT,
    ip_address TEXT,
    user_agent TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 10. Site Settings / Content Management (CMS Key-Value Store)
CREATE TABLE IF NOT EXISTS site_settings (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL,
    type TEXT DEFAULT 'text' CHECK(type IN ('text', 'image')),
    label TEXT DEFAULT 'Setting',
    category TEXT DEFAULT 'general',
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Seed Default Settings if not present
INSERT INTO site_settings (key, value, type, label, category) VALUES
('admission_session', '2026-27', 'text', 'Academic Session / Year', 'admissions'),
('notice_banner_text', 'Admissions for Class XI (Science, Commerce & Arts) for the Academic Session 2026-27 are now open. Collect prospectus from the college office.', 'text', 'Official Notice Banner Text', 'notices'),
('hero_motto', 'KNOWLEDGE • DISCIPLINE • CHARACTER', 'text', 'Hero Motto Line', 'hero'),
('hero_title', 'Shriman G. R. Warange Junior College', 'text', 'Hero Title', 'hero'),
('hero_subtitle', 'Providing quality higher secondary education in Malkapur. We are committed to fostering academic excellence, moral values, and preparing students for competitive examinations and university studies across Science, Commerce, and Arts.', 'text', 'Hero Subtitle Paragraph', 'hero'),
('stat_years', '25+ Years', 'text', 'Years of Educational Service', 'stats'),
('stat_pass_rate', '98.4%', 'text', 'HSC Board Pass Rate', 'stats'),
('stat_students', '1,200+', 'text', 'Students Enrolled Counter', 'stats'),
('contact_phone', '+91 02329 222100', 'text', 'Contact Phone Number', 'contact'),
('contact_email', 'info@warangecollege.edu.in', 'text', 'Contact Email Address', 'contact'),
('contact_address', 'Shriman G. R. Warange Junior College, Malkapur, Shahuwadi, Maharashtra — 415101', 'text', 'Postal Address', 'contact'),
('office_hours', '7:30 AM to 12:00 PM (Morning Shift)', 'text', 'Office Hours', 'contact'),
('img_assembly', 'https://raw.githubusercontent.com/not-amey/clgsite/main/prayer.png', 'image', 'Campus Assembly Photo', 'images'),
('img_lab', 'https://raw.githubusercontent.com/not-amey/clgsite/main/lab.png', 'image', 'Science Laboratory Photo', 'images'),
('img_principal', 'https://raw.githubusercontent.com/not-amey/clgsite/main/lab.png', 'image', 'Principal Message Image', 'images')
ON CONFLICT (key) DO NOTHING;

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_students_dept ON students(department_id);
CREATE INDEX IF NOT EXISTS idx_faculty_dept ON faculty(department_id);
CREATE INDEX IF NOT EXISTS idx_courses_dept ON courses(department_id);
CREATE INDEX IF NOT EXISTS idx_notices_published ON notices(is_published, publish_date);
CREATE INDEX IF NOT EXISTS idx_audit_admin ON audit_logs(admin_id);
CREATE INDEX IF NOT EXISTS idx_audit_created ON audit_logs(created_at);
CREATE INDEX IF NOT EXISTS idx_resets_hash ON password_resets(token_hash);
